### ISSUE TITLE
Project Requirements:

### ISSUE THREAD

**Issue by SebastianMuzalewski** [SebastianMuzalewski/Distribution-Centre#1]
### Pre-requirements:
- [x] Project is done in group of 4 students
- [x] GitHub as a collaboration tool

### Project Requirement Features:
- [ ] As an administrator you should be able to see all distribution centers available to you, admin page can be augmented for this - **5%**
- [x] Distribution Centre Manager should be a separate Spring Boot Project as a REST API protected by basic web security(username/password) - **5%** 
- [x] Distribution center app should have following models: distribution center (id, name, items available, latitude, longitude), Item (same as in clothes warehouse). Important: we should add quantity to the item model - **3%** 
- [x] Distribution center should expose following endpoints: add item to distribution center, delete item, list all distribution centers, request item by brand and name - **3.5%** 
- [x] Database interaction for all the above methods should be supported - **3.5%** 
- [ ] Create two Spring profiles for distribution center with different data sources: H2 for dev and PostgreSQL for QA, please use Docker for Postgres DB and make sure that all operations work correctly - **5%** 
- [ ] Create a form on the admin distribution center page to request item by brand and name, logic should be the following **4%**:
       - Form contains two fields: name and brand dropdown and submit button
       - On form submission we should check which distribution Centre contains items for these parameters
       - Between centers with available items items should be requested from the closest center to the warehouse (warehouse 
          should have GTA area coordinates, exact location is up to you), you should have at least 4 distribution centers and be 
          able to clearly show me that logic works
        - If successful, stock should be replenished in warehouse and deducted from distribution center from which we get the 
          item, else we are redirected to the error page that contains message that stock can’t be replenished
- [x] Add bootstrap styling to all components **1%** 

### Side Features:
- [x] Navbar Implementation
- [x] User sign-in page with optional image as avatar
- [x] Finish Home page
- [x] Finish About page
- [ ] Postman functionality

### Bugs/Issues:
- [x] Update icons for new pages
- [x] Pagination does not currently  function

**Comment by Sniperplank** [comment]
ToDo:
- Add appropriate icon for centers link in the navbar
